package physics;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JSpinner;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SettingsPanel.java
 *
 * Created on 2009-5-16, 22:09:29
 */
/**
 *
 * @author User
 */
public class SettingsPanel extends javax.swing.JPanel {

    private int angle = 10;
    private AnimationPanel animPanel;

    /** Creates new form SettingsPanel */
    public SettingsPanel(AnimationPanel animPnl) {
        initComponents();
        this.animPanel = animPnl;
        setBorder(BorderFactory.createLineBorder(Color.BLACK));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        speedLabel = new javax.swing.JLabel();
        angleLabel = new javax.swing.JLabel();
        accelLabel = new javax.swing.JLabel();
        decrementBtn = new javax.swing.JButton();
        incrementBtn = new javax.swing.JButton();
        speedTxt = new javax.swing.JTextField();
        angleTxt = new javax.swing.JTextField();
        accelTxt = new javax.swing.JTextField();
        topLbl = new javax.swing.JLabel();
        downLbl = new javax.swing.JLabel();
        upLbl = new javax.swing.JLabel();
        speedSpinner = new javax.swing.JSpinner();

        speedLabel.setFont(new java.awt.Font("Arial Black", 0, 14));
        speedLabel.setText("Speed: ");

        angleLabel.setFont(new java.awt.Font("Arial Black", 0, 14));
        angleLabel.setText("Angle: ");

        accelLabel.setFont(new java.awt.Font("Arial Black", 0, 14));
        accelLabel.setText("Acceleration: ");

        decrementBtn.setLabel("<");

        incrementBtn.setText(">");
        incrementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incrementBtnActionPerformed(evt);
            }
        });

        speedTxt.setText("0");

        angleTxt.setText("0");

        accelTxt.setText("0");
        accelTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accelTxtActionPerformed(evt);
            }
        });

        topLbl.setFont(new java.awt.Font("Arial Black", 0, 14));
        topLbl.setText("Adjust Top Positions:");

        downLbl.setFont(new java.awt.Font("Arial", 1, 12));
        downLbl.setText("Down");

        upLbl.setFont(new java.awt.Font("Arial", 1, 12));
        upLbl.setText("Up");

        speedSpinner.setFont(new java.awt.Font("Arial", 0, 12));
        speedSpinner.setModel(new javax.swing.SpinnerNumberModel());
        speedSpinner.setEditor(new JSpinner.NumberEditor(speedSpinner, "#0.00"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accelLabel)
                            .addComponent(angleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(speedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(accelTxt)
                            .addComponent(angleTxt)
                            .addComponent(speedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(decrementBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(incrementBtn)))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(downLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(upLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(speedSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(incrementBtn)
                    .addComponent(decrementBtn))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(angleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accelLabel)
                    .addComponent(accelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(topLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(downLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addComponent(speedSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accelTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accelTxtActionPerformed
    }//GEN-LAST:event_accelTxtActionPerformed

    private void incrementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incrementBtnActionPerformed
        setAngle(animPanel);
    }//GEN-LAST:event_incrementBtnActionPerformed

    private void setAngle(AnimationPanel animPnl) {
        animPnl.setAngle(angle);
        angle += 2F;
        System.out.println(angle);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accelLabel;
    private javax.swing.JTextField accelTxt;
    private javax.swing.JLabel angleLabel;
    private javax.swing.JTextField angleTxt;
    private javax.swing.JButton decrementBtn;
    private javax.swing.JLabel downLbl;
    private javax.swing.JButton incrementBtn;
    private javax.swing.JLabel speedLabel;
    private javax.swing.JSpinner speedSpinner;
    private javax.swing.JTextField speedTxt;
    private javax.swing.JLabel topLbl;
    private javax.swing.JLabel upLbl;
    // End of variables declaration//GEN-END:variables
}
